### PR TITLE
"complete suicide" is inconsiderate

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks, @rugk!

**Comment by rugk** [comment]
Strange merging technique, but okay.

**Comment by wooorm** [comment]
I am unsure what you mean?

**Comment by rugk** [comment]
You seem to have merged the commit directly and not this PR so this PR is shown as closed (unmerged) on GitHub.

**Comment by wooorm** [comment]
Yes, because I had to fix some stuff. For example, the tests started failing, and the built patterns were not included in your PR.

Also, merging is stupid, rebasing is cool :)

**Comment by rugk** [comment]
Ah okay, thanks for doing so. I did not know there were also tests for this...

**Comment by wooorm** [comment]
No problem

**Pull request closed without merging**
