### PR TITLE
Add an option to ignore specific terms

### PR DESCRIPTION
**Pull request by agnoster**
This allows specifically ignoring certain terms by doing e.g.

```js
equality.config.ignoreTerms = {
    host: 'a computer server',
    pop: 'operating on a data structure'
};
```

I have some misgivings about this particular manner of configuration (reaching in and modifying an object in-place) but it seems like the simplest way to do this without changing the API at all and maintaining backwards compatibility. Other options include:

  - `equality.ignoreTerms(["host", "pop"])` would add the words to the local ignore table
  - `equality({ ignoreTerms: ["host", "pop"] })` would return an attacher with configuration (this would change `equality` much more significantly, but allow different instances of attachers to have different options, which seems desirable but maybe more trouble than it's worth)

I'm open to any other way to attach options. Also it may be desirable to remove the terms from the patterns and lookup tables, rather than simply ignoring them in `check()`, but this was by far the easiest and least invasive way of doing it, and the performance downsides (given we're doing a lookup on an object) seem minimal

### CODE REVIEW

**Comment by agnoster** [comment]
If you like this, I'd also like to investigate other configure options - one specifically I have in mind is being able to configure it so that "he/she" is also a warning (since it excludes people who don't identify as gender binary) and (as mentioned elsewhere) specific names which trigger allowing gendered pronouns.

**Comment by agnoster** [comment]
Also I should point out I'm more than happy to implement one of the other configuration styles, but it always feels a bit presumptuous to come into someone else's project and do serious restructuring. If you like in principle doing something like having a "default instance" of the attacher which also has a method to create a custom attacher (so that it wouldn't break backwards compatibility) I could do that, too.

I have to say though I really like the clean, functional way in which retext-equality is implemented and I'm kind of loathe to make it more object-oriented. I might go with a simple closure-generator where you do either `retext.use(equality)` or `retext.use(equality.withConfig({ ... }))`? At any rate this is definitely the main thing blocking me from making this part of our CI so I'm eager to do what it takes to get the pull request accepted (I hate either vendoring in packages or depending on a github fork that may diverge from the mainline)

**Comment by wooorm** [comment]
Thanks a lot! I'll reply more in depth soon.

However, I really appreciate the time and thought you put into this! But, I'd prefer the use of standard retext options. As in, the second argument to 'attacher'. Read more about it in the docs: https://github.com/wooorm/retext/blob/master/readme.md#function-attacherretext-options

**Comment by agnoster** [comment]
Ahhhh I didn't know about standard retext options, that sounds much better!

Would you be interested in me changing this to that form, or do you have your own plans and I should abandon this?

FWIW what I'm doing right now is just building an internal version with a custom list of patterns (as there are also some patterns not present in `retext-equality` we'd like to check for), so there's no rush from my side, but I'm also happy to help :-)

**Comment by wooorm** [comment]
I’d love it if you would be able to find the time to implement this here in retext-equality, @agnoster. Also: really cool that Asana is intending to use alex / retext-equality :+1:

You mentioned patterns you’re using internally, I’d be interested in hearing what those are! Of course, I can imagine that you’d like to keep some private :wink:

I’d go for a method where the second argument passed to `retext.use()` by users, given as the second argument to **retext-equality**s `attacher`, be an options object with a `allow` (maybe a different naming) array of strings (maybe a hash, curious to know why you opted for a dictionary mapping between words and different descriptions here?)

There’s also the fact that some phrasing can include multiple words, e.g., `man made`. Am I correct in assuming your PR doesn’t handle this? One could only `allow` either `man` or `made` to disallow this phrase from matching?

**Comment by wooorm** [comment]
Regarding https://github.com/wooorm/retext-equality/pull/7#issuecomment-148863912:

This could probably be handled in a way where the `or` pattern is handled as `simple`. I’m not sure if the `or` pattern would ever be useful for non-gender patterns (as `"or"` is by definition binary!)

**Comment by agnoster** [comment]
I'm definitely interested in implementing this! Will update the PR when I get a chance. 




At Asana we are currently using gulp-alex to check our entire website (including job descriptions and internal docs) automatically. I'm happy to say that it only found a few issues but they're fixed now :-)




One example of an internal pattern is we decided we don't like the term "non-technical" to describe roles, as it could be seen by some as devaluing non-engineering work which is still in some sense technical. That's not *generally* a phrase everyone should avoid, though, just something we prefer other phrases for. 




I think you're right and this doesn't handle multi-word phrases. Any good suggestions of how best to do that?




And yeah, internally I just bound "simple" to "or" since the reason I initially started integrating this was after we replaced "men and women" with "people". To be honest, I almost would propose this be done generally, it's more inclusive on people who don't identify as gender binary.

**Comment by wooorm** [comment]
Maybe it’s simplest to create a new `whitelist` pattern which works exactly like `simple` but doesn’t warn (just moves the pointer forward so other patterns do not match).

Then, upon attaching, a custom [`byWord` and `byId`](https://github.com/wooorm/retext-equality/blob/42bf0555242316552cf4171c962af6014b451781/lib/equality.js#L26-L27) dictionary is created, the `allow`ed phrases are [expanded](https://github.com/wooorm/retext-equality/blob/42bf0555242316552cf4171c962af6014b451781/lib/equality.js#L39-L53)!

**Comment by wooorm** [comment]
@agnoster Ping! Still interested in working on this?

**Comment by agnoster** [comment]
Still interested, in principle - but not had a lot of bandwidth to tackle. :-( I've got a task to track this and will get to it Someday, but if you feel strongly about getting it done I won't feel bad if you beat me to it, either :-)

**Comment by wooorm** [comment]
Thanks for getting back to me, @agnoster. I of course understand time limitations, as I myself am pressed for time too. I hope to be able to get to this soon, but can’t promise anything. Let’s just leave it pending for now until someone finds the time! :+1:

**Comment by agnoster** [comment]
Sounds good!

**Comment by wooorm** [comment]
This was closed by fea3f1a. Thanks so much for the ideas though :+1:

**Comment by agnoster** [comment]
Awesome work, thanks so much!

:heart:

**Pull request closed without merging**
